import pandas as pd

# Load the data
df = pd.read_csv('C:/Users/Administrator/Desktop/EvenOdd/engineered_features.csv')

# Check for the existence of necessary columns
if 'tick' not in df.columns:
    raise ValueError("The 'tick' column is missing from the dataset.")

# Calculate 'tick_diff' and 'moving_avg' if they don't exist
if 'tick_diff' not in df.columns:
    df['tick_diff'] = df['tick'].diff()

if 'moving_avg' not in df.columns:
    df['moving_avg'] = df['tick'].rolling(window=5).mean()

# Drop rows with NaN values generated by diff() and rolling() operations
df.dropna(inplace=True)

# Save the updated DataFrame
df.to_csv('C:/Users/Administrator/Desktop/EvenOdd/engineered_features_updated.csv', index=False)

print("Updated DataFrame saved with 'tick_diff' and 'moving_avg' features.")
